Starting DFC2021 baseline training script at 2021-02-18 16:43:33.215518
The output directory doesn't exist or is empty.
We will be training with 14062 batches per epoch
Traceback (most recent call last):
  File "train.py", line 195, in <module>
    main()
  File "train.py", line 135, in main
    model = model.to(device)
  File "/home/tanrui@corp.sse.tongji.edu.cn/.conda/envs/dfc2021/lib/python3.8/site-packages/torch/nn/modules/module.py", line 612, in to
    return self._apply(convert)
  File "/home/tanrui@corp.sse.tongji.edu.cn/.conda/envs/dfc2021/lib/python3.8/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/tanrui@corp.sse.tongji.edu.cn/.conda/envs/dfc2021/lib/python3.8/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/tanrui@corp.sse.tongji.edu.cn/.conda/envs/dfc2021/lib/python3.8/site-packages/torch/nn/modules/module.py", line 381, in _apply
    param_applied = fn(param)
  File "/home/tanrui@corp.sse.tongji.edu.cn/.conda/envs/dfc2021/lib/python3.8/site-packages/torch/nn/modules/module.py", line 610, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: out of memory
